[project]
name = "ffdice"
dynamic = [
  "version"
]
authors = [
  { name="mzilverberg", email="maarten@mzilverberg.nl" },
]
description = "A basic random number generator (RNG) that can be used for multiple purposes, such as rolling dice."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.version]
path = "ffdice/__about__.py"

[project.urls]
"Homepage" = "https://github.com/mzilverberg/ffdice"
"Bug Tracker" = "https://github.com/mzilverberg/ffdice/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.bumpversion]
current_version = "1.1.0"
serialize = [
    "{major}.{minor}.{patch}.{pre_l}{$pre_n}",
    "{major}.{minor}.{patch}",
]
message = "Version updated from {current_version} to {new_version}"
pre_commit_hooks = ["uv sync --upgrade", "git add uv.lock"]

[tool.bumpversion.parts.pre_l]
values = ["dev", "rc", "final"]

[[tool.bumpversion.files]]
filename = "ffdice/__about__.py"