name: Create release, and publish Python 🐍 distribution 📦 to TestPyPI

# Action is triggered on every push to the repository, but not on the main branch.
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'What kind of release is this?'
        required: true
        default: 'dev'
        type: choice
        options:
        - auto
        - major
        - minor
        - patch
        - dev

jobs:
  bump-version:
    name: Bump development version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get current version 🔍
      id: get_version
      run: |
        CURRENT_VERSION=$(sed 's/.*"\([^"]*\)".*/\1/' ffdice/__about__.py)
        echo "The current version is $CURRENT_VERSION"
        echo "CURRENT_VERSION=$CURRENT_VERSION >> $GITHUB_ENV
    - name: Define new alpha version 🔤
      id: bump
      uses: callowayproject/bump-my-version@master
      with:
        args: ${{ inputs.bump-type }}
    - name: Output new version 🔖
      run: echo "New version is ${{ steps.bump.outputs.new_version }}"

  # build:
  #   name: Build distribution 📦
  #   needs:
  #   - bump-version
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v6
  #     with:
  #       persist-credentials: false
  #   - name: Set up Python
  #     uses: actions/setup-python@v6
  #     with:
  #       python-version: '3.x'
  #   - name: Install pypa/build
  #     run: >-
  #       python3 -m 
  #       pip install
  #       build
  #       --user
  #   - name: Build a binary wheel and source tarball
  #     run: python3 -m build
  #   - name: Store the distribution packages
  #     uses: actions/upload-artifact@v5
  #     with:
  #       name: python-package-distributions
  #       path: dist/

  # publish-to-testpypi:
  #   name: Publish Python 🐍 distribution 📦 to TestPyPI
  #   needs:
  #   - build
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: testpypi
  #     url: https://test.pypi.org/p/ffdice

  #   permissions:
  #     id-token: write
    
  #   steps:
  #   - name: Download all the dists
  #     uses: actions/download-artifact@v6
  #     with:
  #       name: python-package-distributions
  #       path: dist/
  #   - name: Publish distribution 📦 to TestPyPI
  #     uses: pypa/gh-action-pypi-publish@release/v1
  #     with:
  #       repository-url: https://test.pypi.org/legacy/