name: Publish Python 🐍 distribution 📦 to TestPyPI

# Action is triggered on every push to the repository, but not on the main branch.
on:
  push:
    branches-ignore:
      - main

# Initialize variable for package version.
# This suppresses the 'Context access might be invalid' warning.
env:
  VERSION: ''

jobs:
  bump-version:
    name: Bump development version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Define new development version 🆕
      id: semver
      uses: PaulHatch/semantic-version@v6.0.0
      with:
        tag_prefix: ""
        major_pattern: "/!:|BREAKING:/"
        minor_pattern: "/feat:/"
        version_format: "${major}.${minor}.${patch}-dev${increment}"
        namespace: "dev"
    - name: Output new version 🔖
      run: echo "New version is ${{ steps.semver.outputs.version }}" >> $GITHUB_ENV
    - name: Bump Python package version 🐍
      uses: DamianReeves/write-file-action@v1.3
      with:
        path: ffdice/__about__.py
        contents: |
          __version__ = "${{ env.VERSION }}"
        write-mode: overwrite
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v7.1.0
      with:
        commit_message: "ci: Version bump [ignore]"
        file_pattern: ffdice/*.py

  # build:
  #   name: Build distribution 📦
  #   needs:
  #   - bump-version
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v6
  #     with:
  #       persist-credentials: false
  #   - name: Set up Python
  #     uses: actions/setup-python@v6
  #     with:
  #       python-version: '3.x'
  #   - name: Install pypa/build
  #     run: >-
  #       python3 -m 
  #       pip install
  #       build
  #       --user
  #   - name: Build a binary wheel and source tarball
  #     run: python3 -m build
  #   - name: Store the distribution packages
  #     uses: actions/upload-artifact@v5
  #     with:
  #       name: python-package-distributions
  #       path: dist/

  # publish-to-testpypi:
  #   name: Publish Python 🐍 distribution 📦 to TestPyPI
  #   needs:
  #   - build
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: testpypi
  #     url: https://test.pypi.org/p/ffdice

  #   permissions:
  #     id-token: write
    
  #   steps:
  #   - name: Download all the dists
  #     uses: actions/download-artifact@v6
  #     with:
  #       name: python-package-distributions
  #       path: dist/
  #   - name: Publish distribution 📦 to TestPyPI
  #     uses: pypa/gh-action-pypi-publish@release/v1
  #     with:
  #       repository-url: https://test.pypi.org/legacy/